### PR TITLE
Update alpine version to 3.11

### PR DESCRIPTION
**Pull request by sahilrajput03**
#### Before:

image

#### After using -k flag, 

image

### CODE REVIEW

**Comment by sahilrajput03** [comment]
Source of knowlege: https://stackoverflow.com/a/24618403

**Comment by qzuw** [comment]
It is probably better to update alpine image version than to disable certificate check.

Both alpine:3.10 and alpine:3.11 seem to work, newer versions than those need further changes due alpine renaming python package.

**Comment by sahilrajput03** [comment]
Thanks @qzuw , 
image

### It works now!!

**Comment by Jakousa** [comment]
Hey, thanks for the PR, unfortunately I had already made conflicting changes when I noticed your PR so I updated the version to 3.13.

**Pull request closed without merging**
